apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb324
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lb324
  template:
    metadata:
      labels:
        app: lb324
    spec:
      containers:
        - name: lb324-app
          image: agachan/lb324:v1
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: lb324-service
spec:
  selector:
    app: lb324
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30003
